BATCH_SIZE: 1
DECAY: 5.0e-05
EPOCH: 5
FP_MLP_0:
- 64
- 64
FP_MLP_1:
- 64
- 32
FP_MLP_2:
- 32
- 32
- 32
LR: 0.001
NUM_POINTS: 2048
RAW_NUM_POINTS: 20000
SAVE_BEST_ONLY: true
SA_MLP_GROUP_ALL:
- 64
- 128
- 256
SA_MLP_LIST_0:
- - 8
  - 8
  - 16
- - 16
  - 16
  - 32
- - 16
  - 24
  - 32
SA_MLP_LIST_1:
- - 16
  - 16
  - 32
- - 32
  - 32
  - 64
- - 32
  - 32
  - 64
SA_MLP_LIST_2:
- - 16
  - 16
  - 32
- - 32
  - 32
  - 64
- - 32
  - 32
  - 64
SA_NPOINT_0: 2048
SA_NPOINT_1: 128
SA_NPOINT_2: 32
SA_NSAMPLE_LIST_0:
- 8
- 16
- 32
SA_NSAMPLE_LIST_1:
- 16
- 16
- 32
SA_NSAMPLE_LIST_2:
- 16
- 16
- 32
SA_RADIUS_LIST_0:
- 0.02
- 0.04
- 0.08
SA_RADIUS_LIST_1:
- 0.04
- 0.08
- 0.16
SA_RADIUS_LIST_2:
- 0.08
- 0.016
- 0.32
